# Generated by Django 4.0.1 on 2022-02-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
