# Generated by Django 4.0.1 on 2022-02-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pot_item',
            field=models.ManyToManyField(related_name='pot_item', to='api.Pot'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_item',
            field=models.ManyToManyField(related_name='product_item', to='api.Product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
