# Generated by Django 4.0.1 on 2022-02-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cart_pot_item_remove_cart_product_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pot',
            new_name='pot_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
