# Generated by Django 4.0.1 on 2022-02-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cart_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pot_id',
            new_name='pot',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
