# Generated by Django 4.0.1 on 2022-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cartitem_fertilizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('online', 'Email Payment Receipt'), ('cod', 'Cash on Delivery')], default='online', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fertilizer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'Onsite Pick-up'), ('delivery', 'Delivery for Service')], default='pickup', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Collect'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
