# Generated by Django 4.0.1 on 2022-02-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='fertilizer_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pot_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fertilizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_fertilizer', to='api.fertilizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_pot', to='api.pot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='api.product'),
            preserve_default=False,
        ),
    ]
