# Generated by Django 4.0.2 on 2022-02-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plant_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_tip', to='api.planttip'),
        ),
    ]
