# Generated by Django 4.0.2 on 2022-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_plant_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttip',
            name='name',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
    ]
