# Generated by Django 4.0.2 on 2022-02-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_planttip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planttip',
            old_name='fertilizer_type',
            new_name='humidity',
        ),
    ]
