# Generated by Django 4.0.2 on 2022-02-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_fertilizer_type_planttip_humidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttip',
            name='temperature',
        ),
    ]
