# Generated by Django 4.0.2 on 2022-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_planttip_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
